[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start:sqlite"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
NODE_ENV = "production"
NPM_CONFIG_OMIT = "dev"
