[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start:sqlite"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
USE_SQLITE = "true"
