[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start:sqlite"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Configuración para SQLite (sin servicio de base de datos)
[[services]]
name = "web"
source = "."

# Variables de entorno para el servicio web
[services.web.environment]
NODE_ENV = "production"
PORT = "3000"
USE_SQLITE = "true"
